apiVersion: v1
kind: Service
metadata:
  name: phpma-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: phpma
  type: LoadBalancer
  loadBalancerIP: 192.168.99.150
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpma-deployment
  labels:
    app: phpma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpma
  template:
    metadata:
      labels:
        app: phpma
    spec:
      containers:
      - name: phpma
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        image: phpma_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000