version: '3.8'
services:

  nginx:
    build: 
      context: ./nginx/
      args:
        user: ${USER}
        ssl_body: ${SSL_BODY}
        domian: ${DOMIAN}
    container_name: inception_nginx
#    volumes:      
#      - wordpress:/var/www/${DOMIAN}/wordpress/
    ports:
      - "443:443"
      - "80:80"
#    networks:
#      - inception
#    depends_on:
#      - wordpress
#   command: 
#      - /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf" 

#  mariadb:
#    build: ./mariadb/
#    container_name: inception_mariadb
#    env_file: 
#      - .env
#    restart: always
#    volumes:
#      - mariadb:/var/lib/mysql
 
#  wordpress:
#    build: ./wordpress/
#    container_name: inception_wordpress
#    restart: always
#    depends_on:
#      - mariadb
#    env_file: 
#      - .env
#    volumes:      
#      - wordpress:/var/www/${DOMIAN}/wordpress/
#    networks: 
#      - inception

#volumes:
#  wordpress:
#    name: wordpress
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: "${PATH_VOL}/wordpress"
#      
#  mariadb:
#    name: mariadb
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: "${PATH_VOL}/mysql"
      

#networks:
#  inception:
#    name: "inception"