version: '3.8'
services:

  nginx:
    build: ./srcs/nginx/
    container_name: inc_nginx
    env_file: 
      .env
    restart: always
    ports: 
      - 443:443
    volumes:
      - /home/${USER}/data/wordpress-files:/var/www/${USER}.42.fr/
 

  mariadb:
    build: ./srcs/mariadb/
    container_name: inc_mariadb
    env_file: 
      .env
    restart: always
    volumes:
      - /home/${USER}/data/wordpress-files:/var/www/${USER}.42.fr/

  
  wp:
    build: ./srcs/wp/
    container_name: inc_wp
    restart: always
    depends_on:
      - mariadb
      - nginx
    env_file: 
      - .env
    volumes:
      - /home/${USER}/data/wordpress-files:/var/www/${USER}.42.fr/
