version: '3.8'
services:

  nginx:
    build: 
      context: ./srcs/nginx/
      args:
        user: ${USER}
        ssl_body: ${SSL_BODY}
        domian: ${DOMIAN}
    container_name: inception_nginx
    volumes:
      - ${PATH_VOL}/wordpress-files:/var/www/42.fr/
    ports:
      - "443:443"
    networks:
      - localhost

  mariadb:
    build: ./srcs/mariadb/
    container_name: inception_mariadb
    env_file: 
      .env
    restart: always
    volumes:
      - ${PATH_VOL}/wordpress-files:/var/www/42.fr/
  
  wordpress:
    build: ./srcs/wordpress/
    container_name: inception_wordpress
    restart: always
    depends_on:
      - mariadb
    env_file: 
      - .env
    volumes:
      - ${PATH_VOL}/wordpress-files:/var/www/42.fr/
    networks: 
      - localhost

networks:
  localhost:
    name: inet